### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by DmitrijOkeanij** [goriunov/vuejs-rollup-boilerplate#1]
Very thanks for this template.
Whole day trying to run Vue on Rollup, but not with full success.
Trying your template, it is full work and up to date.

**Comment by goriunov** [comment]
Hi, I am happy that everything works. If you will have any problems just open an issue :) I have updated some stuff in Template (remove no more needed package and update dependencies) so would suggest to clone new version. 

Thank you.
